import {FilesetResolver,HandLandmarker} from '@mediapipe/tasks-vision'

const MODEL='https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task'
const WASM='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm'
const LINKS=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]]
const TIPS=[4,8,12,16,20],skin=new THREE.MeshStandardMaterial({color:'#B97852',roughness:.82}),sleeve=new THREE.MeshStandardMaterial({color:'#0B67C8',roughness:.74}),fingerGeometry=new THREE.CylinderGeometry(.022,.026,1,8),armGeometry=new THREE.CylinderGeometry(.085,.125,1,10),palmGeometry=new THREE.SphereGeometry(.145,14,10),tipGeometry=new THREE.SphereGeometry(.032,8,6)
const up=new THREE.Vector3(0,1,0),direction=new THREE.Vector3(),middle=new THREE.Vector3(),targetQuaternion=new THREE.Quaternion(),anchor=new THREE.Vector3(),elbow=new THREE.Vector3()
let detector,stream,running=false,lastTime=-1,lastRun=0,frameId=0

function mesh(geometry,material){const item=new THREE.Mesh(geometry,material);item.visible=false;return item}
function makeHand(){const root=new THREE.Group(),upper=mesh(armGeometry,sleeve),forearm=mesh(armGeometry,skin),palm=mesh(palmGeometry,skin),bones=LINKS.map(()=>mesh(fingerGeometry,skin)),tips=TIPS.map(()=>mesh(tipGeometry,skin)),points=Array.from({length:21},()=>new THREE.Vector3());palm.scale.set(1,.74,.38);root.add(upper,forearm,palm,...bones,...tips);return{root,upper,forearm,palm,bones,tips,points}}
const hands=[makeHand(),makeHand()]
function moveBone(item,a,b){const wasVisible=item.visible;direction.subVectors(b,a);const length=direction.length();if(length<.001){item.visible=false;return}middle.copy(a).add(b).multiplyScalar(.5);targetQuaternion.setFromUnitVectors(up,direction.normalize());if(wasVisible){item.position.lerp(middle,.58);item.quaternion.slerp(targetQuaternion,.58)}else{item.position.copy(middle);item.quaternion.copy(targetQuaternion)}item.scale.set(1,length,1);item.visible=true}
function mapPoint(output,input){output.set((input.x-.5)*2.65,(.5-input.y)*1.65,-1.75-input.z*.85)}
function hide(hand){hand.upper.visible=false;hand.forearm.visible=false;hand.palm.visible=false;hand.bones.forEach(item=>item.visible=false);hand.tips.forEach(item=>item.visible=false)}
function draw(result){const landmarks=(result.landmarks||[]).slice(0,2);landmarks.forEach((marks,index)=>{const hand=hands[index];marks.forEach((mark,i)=>mapPoint(hand.points[i],mark));const wrist=hand.points[0];anchor.set(wrist.x<0?-1.18:1.18,-1.08,-1.9);elbow.copy(anchor).lerp(wrist,.52);moveBone(hand.upper,anchor,elbow);moveBone(hand.forearm,elbow,wrist);middle.copy(wrist).lerp(hand.points[9],.56);hand.palm.position.lerp(middle,hand.palm.visible ? .58 : 1);hand.palm.visible=true;LINKS.forEach((link,i)=>moveBone(hand.bones[i],hand.points[link[0]],hand.points[link[1]]));TIPS.forEach((tip,i)=>{hand.tips[i].position.lerp(hand.points[tip],hand.tips[i].visible ? .58 : 1);hand.tips[i].visible=true})});for(let i=landmarks.length;i<hands.length;i++)hide(hands[i])}
async function loop(now){if(!running)return;const video=document.querySelector('#hand-camera');if(video.readyState>=2&&video.currentTime!==lastTime&&now-lastRun>100){lastTime=video.currentTime;lastRun=now;try{draw(detector.detectForVideo(video,Math.round(now)))}catch{}}frameId=requestAnimationFrame(loop)}
async function createDetector(){const vision=await FilesetResolver.forVisionTasks(WASM),options={baseOptions:{modelAssetPath:MODEL,delegate:'GPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.55,minHandPresenceConfidence:.5,minTrackingConfidence:.55};try{return await HandLandmarker.createFromOptions(vision,options)}catch{options.baseOptions.delegate='CPU';return HandLandmarker.createFromOptions(vision,options)}}
async function start(button){button.disabled=true;button.textContent='PREPARANDO CÂMERA…';try{detector??=await createDetector();stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:480,max:640},height:{ideal:360,max:480},frameRate:{ideal:20,max:24}}});const video=document.querySelector('#hand-camera');video.srcObject=stream;await video.play();hands.forEach(hand=>document.querySelector('#camera').object3D.add(hand.root));running=true;button.textContent='DESATIVAR BRAÇOS';button.dataset.active='true';frameId=requestAnimationFrame(loop)}catch(error){button.textContent='CÂMERA NÃO LIBERADA';console.warn(error)}finally{button.disabled=false}}
function stop(button){running=false;cancelAnimationFrame(frameId);stream?.getTracks().forEach(track=>track.stop());stream=null;hands.forEach(hide);button.textContent='ATIVAR BRAÇOS';button.dataset.active='false'}
window.addEventListener('DOMContentLoaded',()=>{const button=document.querySelector('#camera-arms');if(!navigator.mediaDevices?.getUserMedia){button.disabled=true;button.textContent='CÂMERA INDISPONÍVEL';return}button.addEventListener('click',()=>button.dataset.active==='true'?stop(button):start(button))})
