import {FilesetResolver,HandLandmarker} from '@mediapipe/tasks-vision'

const MODEL='https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task'
const WASM='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm'
const LINKS=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]]
let detector,stream,running=false,lastTime=-1,lastRun=0,frameId=0

function bone(color='#FDBA18',radius=.025){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,1,8),new THREE.MeshStandardMaterial({color,roughness:.7}));mesh.visible=false;return mesh}
function makeHand(){const root=new THREE.Group(),forearm=bone('#0B67C8',.09),palm=new THREE.Mesh(new THREE.SphereGeometry(.13,12,8),new THREE.MeshStandardMaterial({color:'#0B67C8',roughness:.72})),bones=LINKS.map(()=>bone());palm.scale.set(1,.72,.42);palm.visible=false;root.add(forearm,palm,...bones);return{root,forearm,palm,bones}}
const hands=[makeHand(),makeHand()],up=new THREE.Vector3(0,1,0)
function setBone(mesh,a,b){const direction=new THREE.Vector3().subVectors(b,a),length=direction.length();mesh.visible=length>.001;mesh.position.copy(a).add(b).multiplyScalar(.5);mesh.scale.set(1,length,1);mesh.quaternion.setFromUnitVectors(up,direction.normalize())}
function point(p){return new THREE.Vector3((p.x-.5)*2.65,(.5-p.y)*1.65,-1.75-p.z*.85)}
function hide(hand){hand.forearm.visible=false;hand.palm.visible=false;hand.bones.forEach(mesh=>mesh.visible=false)}
function draw(result){hands.forEach(hide);(result.landmarks||[]).slice(0,2).forEach((marks,index)=>{const hand=hands[index],points=marks.map(point),wrist=points[0],anchor=new THREE.Vector3(wrist.x<0?-1.12:1.12,-1.05,-1.85);setBone(hand.forearm,anchor,wrist);hand.palm.visible=true;hand.palm.position.copy(points[0]).lerp(points[9],.55);LINKS.forEach((link,i)=>setBone(hand.bones[i],points[link[0]],points[link[1]]))})}
async function loop(now){if(!running)return;const video=document.querySelector('#hand-camera');if(video.readyState>=2&&video.currentTime!==lastTime&&now-lastRun>65){lastTime=video.currentTime;lastRun=now;try{draw(detector.detectForVideo(video,Math.round(now)))}catch{}}frameId=requestAnimationFrame(loop)}
async function start(button){button.disabled=true;button.textContent='PREPARANDO CÂMERA…';try{if(!detector){const vision=await FilesetResolver.forVisionTasks(WASM);detector=await HandLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:MODEL,delegate:'GPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.55,minHandPresenceConfidence:.5,minTrackingConfidence:.5})}stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:640,max:960},height:{ideal:480,max:720},frameRate:{ideal:24,max:30}}});const video=document.querySelector('#hand-camera');video.srcObject=stream;await video.play();hands.forEach(hand=>document.querySelector('#camera').object3D.add(hand.root));running=true;button.textContent='DESATIVAR BRAÇOS';button.dataset.active='true';frameId=requestAnimationFrame(loop)}catch(error){button.textContent='CÂMERA NÃO LIBERADA';console.warn(error)}finally{button.disabled=false}}
function stop(button){running=false;cancelAnimationFrame(frameId);stream?.getTracks().forEach(track=>track.stop());stream=null;hands.forEach(hide);button.textContent='ATIVAR BRAÇOS';button.dataset.active='false'}
window.addEventListener('DOMContentLoaded',()=>{const button=document.querySelector('#camera-arms');if(!navigator.mediaDevices?.getUserMedia){button.disabled=true;button.textContent='CÂMERA INDISPONÍVEL';return}button.addEventListener('click',()=>button.dataset.active==='true'?stop(button):start(button))})
